server:
  port: 9090

spring:
  application:
    name: RESERVATION-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/reservations}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    properties:
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='7QUPJL4WYN6QCQ73' password='JMfgGPuvsOO2ZobI+lFhtbz45N1tIwL/l6NfjhBEadCU5eDZuhz9Wgr0CRrYbqBv';
      bootstrap:
        servers: pkc-ymrq7.us-east-2.aws.confluent.cloud:9092
      security:
        protocol: SASL_SSL
    consumer:
      group-id: parking-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.codeofus.reservationservice.client: DEBUG

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 5
        wait-duration: 2S
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 40.0f
        wait-duration-in-open-state: 60S
        max-wait-duration-in-half-open-state: 10S
        permitted-number-of-calls-in-half-open-state: 10
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: COUNT_BASED

parking:
  client:
    url: ${PARKING_CLIENT_URL:localhost:8080}