server:
  port: 9090

spring:
  application:
    name: RESERVATION-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/reservations}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.codeofus.reservationservice.client: DEBUG

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 5
        wait-duration: 2S
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 40.0f
        wait-duration-in-open-state: 10S
        #max-wait-duration-in-half-open-state: 10S
        permitted-number-of-calls-in-half-open-state: 10
        sliding-window-type: COUNT_BASED
